#pragma once

#define EBUS_APPNAME "Zebus"
#define EBUS_UART_NUM 1
#define EBUS_UART_RX_PIN 32
#define EBUS_UART_TX_PIN 33

#define EBUS_MASTER_ADDRESS 0x00
#define EBUS_TELEGRAM_HISTORY_QUEUE_SIZE 50
#define EBUS_TELEGRAM_SEND_QUEUE_SIZE 10
#define EBUS_MAX_TRIES 2
#define EBUS_MAX_LOCK_COUNTER 4

#define EBUS_HEATER_MASTER_ADDRESS 0x03

#define EBUS_WIFI_CONFIG_AP_NAME EBUS_APPNAME
#define EBUS_WIFI_CONFIG_AP_PASSWORD_LENGTH 12


