#pragma once

#define UART_FOR_EBUS 1
#define EBUS_UART_RX_PIN 32
#define EBUS_UART_TX_PIN 33

#define EBUS_MASTER_ADDRESS 0
#define EBUS_TELEGRAM_HISTORY_QUEUE_SIZE 50
#define EBUS_TELEGRAM_SEND_QUEUE_SIZE 10
