#pragma once

#define EBUS_APPNAME "Zebus"
#define EBUS_UART_NUM 1
#define EBUS_UART_RX_PIN 32
#define EBUS_UART_TX_PIN 33

#define EBUS_MASTER_ADDRESS 0x00
#define EBUS_TELEGRAM_HISTORY_QUEUE_SIZE 50
#define EBUS_TELEGRAM_SEND_QUEUE_SIZE 20
#define EBUS_TELEGRAM_RECEIVE_BYTE_QUEUE_SIZE 1024
#define EBUS_MAX_TRIES 2
#define EBUS_MAX_LOCK_COUNTER 4

#define EBUS_HEATER_MASTER_ADDRESS 0x03

#define EBUS_WIFI_CONFIG_AP_NAME EBUS_APPNAME
#define EBUS_WIFI_CONFIG_AP_PASSWORD_LENGTH 8

#define EBUS_NTP_SERVER "1.be.pool.ntp.org"
#define EBUS_NTP_GMT_OFFSET_SEC 3600
#define EBUS_NTP_GMT_DST_OFFSET_SEC 3600
#define EBUS_NTP_REFRESH_INTERVAL_SEC (5 * 60)
