#ifndef _ZEBUS_CONFIG
#define _ZEBUS_CONFIG

// application configuration
#define ZEBUS_APPNAME "Zebus"

#define ZEBUS_LOG_LEVEL ESP_LOG_DEBUG

#define ZEBUS_WIFI_CONFIG_AP_PASSWORD_LENGTH 8
#define ZEBUS_WIFI_HOSTNAME "zebus.home.arpa"

#define ZEBUS_NTP_SERVER "1.be.pool.ntp.org"
#define ZEBUS_NTP_GMT_OFFSET_SEC 3600
#define ZEBUS_NTP_GMT_DST_OFFSET_SEC 3600
#define ZEBUS_NTP_REFRESH_INTERVAL_SEC (5 * 60)

// eBUS configuration
#define EBUS_UART_NUM 1
#define EBUS_UART_RX_PIN 32
#define EBUS_UART_TX_PIN 33

#define EBUS_MASTER_ADDRESS 0x00
#define EBUS_TELEGRAM_HISTORY_QUEUE_SIZE 50
#define EBUS_TELEGRAM_SEND_QUEUE_SIZE 20
#define EBUS_TELEGRAM_RECEIVE_BYTE_QUEUE_SIZE 1024
#define EBUS_MAX_TRIES 2
#define EBUS_MAX_LOCK_COUNTER 4

#define EBUS_HEATER_MASTER_ADDRESS 0x03

// TFT configuration
#define TFT_SCLK 18
#define TFT_MOSI 23
#define TFT_DC 27
#define TFT_RST 4
#define TFT_RGB_ORDER 0


#endif
